/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PromoWillkommensbonusRouteImport } from './routes/promo.willkommensbonus'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoWillkommensbonusRoute = PromoWillkommensbonusRouteImport.update({
  id: '/promo/willkommensbonus',
  path: '/promo/willkommensbonus',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/promo/willkommensbonus': typeof PromoWillkommensbonusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/promo/willkommensbonus': typeof PromoWillkommensbonusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/promo/willkommensbonus': typeof PromoWillkommensbonusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/promo/willkommensbonus'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/promo/willkommensbonus'
  id: '__root__' | '/' | '/promo/willkommensbonus'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PromoWillkommensbonusRoute: typeof PromoWillkommensbonusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo/willkommensbonus': {
      id: '/promo/willkommensbonus'
      path: '/promo/willkommensbonus'
      fullPath: '/promo/willkommensbonus'
      preLoaderRoute: typeof PromoWillkommensbonusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PromoWillkommensbonusRoute: PromoWillkommensbonusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
